### Generate Parentheses

From: https://leetcode.com/problems/generate-parentheses/description/

Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

For example, given n = 3, a solution set is:

```

[
  "((()))",
  "(()())",
  "(())()",
  "()(())",
  "()()()"
]
```


In [12]:
class Solution(object):
    def generateParenthesis(self, n):
        """
        :type n: int
        :rtype: List[str]
        """
        # N = 3
        # ()()()
        # (())()
        # ((()))
        # ()(())
        # (()())
        #
        # ((()))
        # 6 char...
        #  permutations of 6 char.. find well formed ones from that.
        # a well formed is one.. has matching closing parentheses for every opening parentheses
        #
        # 
        if n <= 0:
            return []
        
        if n == 1:
            return ["()"]
        
        allPairsOfParentheses = "(" * n + ")" * n
        
        permutations = self.genPermutations(allPairsOfParentheses)
        return list(filter(self.isWellFormed, permutations))
        
    
    def isWellFormed(self, parentheses):
        nParentheses = 0
        
        for char in parentheses:
            if char == '(':
                nParentheses += 1
            else:
                # assuming string has only ( or )
                nParentheses -= 1
                if nParentheses < 0:
                    return False
                
        return nParentheses == 0
    
    def genPermutations(self, s):
        
        if len(s) == 1:
            return {s}
        
        if len(s) == 2:
            return {s[0] + s[1], s[1] + s[0]}
        
        permutations = set()
        
        for i, char in enumerate(s):
            remainingText = s[i+1:] + s[:i]
            for perm in self.genPermutations(remainingText):
                permutations.add(char + perm)
        
        return permutations
    

In [11]:
s = Solution()

%timeit s.generateParenthesis(3)
%timeit s.generateParenthesis(4)
%timeit s.generateParenthesis(5)

715 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
40.5 ms ± 1.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.5 s ± 30.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Brute force solution of generating all permutations and check each one for correctness is super expensive. 
I think it takes about O(n*n!) time. 

Sample runs with n = 3, 4, 5 gave the following timings on my machine
```
715 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
40.5 ms ± 1.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.5 s ± 30.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

In [30]:
class Solution(object):
    def generateParenthesis(self, n):
        """
        :type n: int
        :rtype: List[str]
        """
        # N = 3
        # ()()()
        # (())()
        # ((()))
        # ()(())
        # (()())
        #
        # ((()))
        # 
        # using backtracking this time
        
        validParentheses = []
        
        def backtrack(s = "", nOpen = 0, nClosing = 0):
            if len(s) == 2 * n:
                validParentheses.append(s)
            else:
                if nOpen < n:
                    backtrack("(" + s, nOpen + 1, nClosing)
                
                if nClosing < nOpen:
                    backtrack(s + ")", nOpen, nClosing + 1)
                    
        backtrack()
        return validParentheses
                

In [31]:
s = Solution()
print("Timing the backtracking solution...")
%timeit s.generateParenthesis(3)
%timeit s.generateParenthesis(4)
%timeit s.generateParenthesis(5)

Timing the backtracking solution...
8.38 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
23.3 µs ± 822 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
71.1 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


* Number of valid parentheses for given n is the Catalan number (`C(n) = (2n!) / (n+1)!n!`)
* Complexity of the brute force is O(n! * n), which is the worst possible one.
* Complexity of the backtracking solution is governed by the asymptotic value of the Catalan number, which is derived as `O(4^n/(n*sqrt(n))`